CREATE TABLE IF NOT EXISTS Events (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Subscribers (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    link TEXT NOT NULL,
    event_id INTEGER NOT NULL,
    FOREIGN KEY(event_id) REFERENCES Events(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Events_link (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    event_id INTEGER NOT NULL,
    subscriber_id INTEGER NOT NULL,
    link TEXT,
    FOREIGN KEY(event_id) REFERENCES Events(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(subscriber_id) REFERENCES Subscribers(id) ON DELETE CASCADE ON UPDATE CASCADE
)